version: '3'

services:
  medcard-service:
    build: ./medcard_microservice
    container_name: medCardService
    environment:
      - APP_PORT=8080
      - APP_NAME=medCardService
    ports:
      - "8080:8080"
    networks:
    - project-network

  postgres-1:
    build: ./database
    container_name: postgres-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    # user: postgres
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready" ]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    ports:
      - "5432:5432"
    networks:
      - project-network
    

networks:
  project-network:
    name: project-network