GET http://0.0.0.0:8080/medcard_service?uuid=uniqueid
###

POST http://0.0.0.0:8080/medcard_service
Content-Type: application/json

{
  "patient_id": "hi",
  "doctor_id": "str",
  "appointment_id": "str",
  "diagnosis": "str"
}
###