version: '3'

services:

  cassandra-1:
    image: cassandra:latest
    container_name: cassandra-1
    networks:
      - project-network
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=cassandra-1,cassandra-2"

  cassandra-2:
    image: cassandra:latest
    container_name: cassandra-2
    networks:
      - project-network
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=cassandra-1,cassandra-2"
    depends_on:
      - "cassandra-1"
 
  cassandra-3:
    image: cassandra:latest
    container_name: cassandra-3
    networks:
      - project-network
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=cassandra-1,cassandra-2"
    depends_on:
      - "cassandra-2"

  cassandra_temp:
    image: cassandra:latest
    volumes:
      - ./database/scripts/bash:/docker-entrypoint.sh
      - ./database/scripts/cql:/tmp/cql
    networks:
      - project-network
    command: >
      bash ./docker-entrypoint.sh/startup.sh

  schedule-service:
    build: ./microservice
    container_name: scheduleService
    environment:
      - APP_PORT=8081
      - APP_NAME=scheduleService
    ports:
      - "8081:8081"
    networks:
      - project-network

networks:
  project-network:
    name: project-network